jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - run:
          name: Show Details
          command: pwd && ls
      - persist_to_workspace:
          root: .
          paths: example

  install_npm_dependencies:
    working_directory: ./example
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Show Details
          command: pwd && ls
      - rn/yarn_install
      - persist_to_workspace:
          root: .
          paths: .

  start_metro:
    working_directory: ./example
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Show Details
          command: pwd && ls
      - run:
          name: Start Metro Server
          command: yarn start

  test_android:
    working_directory: ./example
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Show Details
          command: pwd && ls
      - rn/android_emulator_start
      - run:
          name: Android E2E Tests
          command: yarn e2e:android

  test_ios:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: ./example
      - run:
          name: Show Details
          command: pwd && ls
      - rn/pod_install
      - run:
          name: iOS E2E Tests
          command: yarn e2e:ios

version: 2.1
orbs:
  rn: react-native-community/react-native@4.4.2
workflows:
  test:
    jobs:
      - checkout_code
      - install_npm_dependencies:
          requires:
            - checkout_code
      - start_metro:
          requires:
            - install_npm_dependencies
      - test_android:
          requires:
            - start_metro
      - test_ios:
          requires:
            - start_metro
