jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - run:
          name: Show Details
          command: pwd && ls
      - persist_to_workspace:
          root: .
          paths: example

  install_npm_dependencies:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          command: >
            mkdir -p ~/.tmp/checksumfiles

            find example -type f -name 'package.json' -not -path "*node_modules*" -exec
            cat {} + >> ~/.tmp/checksumfiles/package.json

            find example -type f -name 'yarn.lock' -not -path "*node_modules*" -exec cat
            {} + >> ~/.tmp/checksumfiles/yarn.lock
          name: Create cache checksum file
      - restore_cache:
          keys:
            - >-
              yarn-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json"
              }}-{{ checksum "~/.tmp/checksumfiles/yarn.lock" }}-{{
              .Environment.CACHE_VERSION }}
      - run:
          command: >-
            cd example && yarn install --frozen-lockfile --non-interactive --cache-folder
            /tmp/yarn
          name: Yarn Install
      - save_cache:
          key: >
            yarn-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json"
            }}-{{ checksum "~/.tmp/checksumfiles/yarn.lock" }}-{{
            .Environment.CACHE_VERSION }}
          paths:
            - /tmp/yarn
      - run:
          name: Show Details
          command: pwd && ls
      - persist_to_workspace:
          root: .
          paths: example

#  start_metro:
#    executor: rn/linux_js
#    steps:
#      - attach_workspace:
#          at: .
#      - run:
#          name: Show Details
#          command: pwd && ls
#      - run:
#          background: true
#          name: Start Metro Server
#          command: cd example && yarn start

  test_android:
    executor: rn/linux_android
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Show Details
          command: pwd && ls
      - run:
          background: true
          name: Start Metro Server
          command: cd example && yarn start
      - rn/android_emulator_start
      - run:
          name: Android E2E Tests
          command: cd example && yarn e2e:android
#
#  test_ios:
#    working_directory: ./example
#    executor: rn/linux_js
#    steps:
#      - attach_workspace:
#          at: .
#      - run:
#          name: Show Details
#          command: pwd && ls
#      - rn/pod_install
#      - run:
#          name: iOS E2E Tests
#          command: yarn e2e:ios

version: 2.1
orbs:
  rn: react-native-community/react-native@4.4.2
workflows:
  test:
    jobs:
      - checkout_code
      - install_npm_dependencies:
          requires:
            - checkout_code
#      - start_metro:
#          requires:
#            - install_npm_dependencies
      - test_android:
          requires:
            - install_npm_dependencies
#      - test_ios:
#          requires:
#            - start_metro
