version: 2.1
orbs:
  react-native: react-native-community/react-native@4.4.2

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  install_npm_dependencies:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: ./example
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - rn/yarn_install
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ./example
          paths:
            - node_modules

  test_android:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: ./example
      - rn/android_emulator_start
      - run:
          name: Android E2E Tests
          command: yarn e2e:android

  test_ios:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: ./example
      - rn/pod_install
      - run:
          name: iOS E2E Tests
          command: yarn e2e:ios

workflows:
  test:
    jobs:
      - checkout_code
      - install_npm_dependencies:
          requires:
            - checkout_code
      - rn/metro_start:
          requires:
            - install_npm_dependencies
      - test_android:
          requires:
            - rn/metro_start
      - test_ios:
          requires:
            - rn/metro_start
