name: Android E2E Tests

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: example
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install npm dependencies
        run: yarn install --no-progress --non-interactive
      - name: Run e2e tests
        run: yarn e2e:android
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/
