name: Android E2E Tests

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test-android:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: example
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install npm denpendencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Run e2e tests
        run: |
          yarn start &
          yarn e2e:start-android-emulator &
          yarn e2e:android
