name: iOS E2E Tests

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  test-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install npm denpendencies
        run: yarn install --frozen-lockfile --non-interactive --silent
      - name: Compilation
        run: yarn build
      - name: Install example npm denpendencies
        run: cd example && yarn install --frozen-lockfile --non-interactive --silent
      - name: Install pod denpendencies
        run: cd ios && pod install --silent && cd -
      - name: Build ios
        run: yarn e2e:build-ios
      - name: Start iOS simulator
        run: xcrun simctl boot "iPhone 11" || true
      - name: Generate umi temp files
        run: yarn generate
      - name: Show details
        run: pwd && ls -a
      - name: Start metro dev server
        run: nohup yarn start > /dev/null 2>&1 &
      - name: Run e2e tests
        run: yarn e2e:run-ios
