name: iOS E2E Tests

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test-ios:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: example
    steps:
      - uses: actions/checkout@v2
      - name: Install npm denpendencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Install pod denpendencies
        run: cd ios && pod install && cd -
      - name: Run e2e tests
        run: yarn e2e:ios
