name: Android E2E Tests

on:
  push:
    tags:
      - v*

jobs:
  test-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: example
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: yarn install
      - name: Run e2e tests
        run: yarn e2e:android
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
